import * as fs from 'fs';
import * as path from 'path';

/**
 * Copy the pre-built website template to the output directory
 * This makes the documentation a fully self-contained static site
 */
export async function copyTemplateToOutput(outputDir: string, verbose?: boolean): Promise<void> {
  // Determine template location
  // In development: template/ directory in project root
  // In production: template/ directory in installed npm package
  const templateDir = findTemplateDirectory();

  if (!fs.existsSync(templateDir)) {
    throw new Error(
      `Template directory not found at ${templateDir}.\n` +
      'The website template needs to be built first.\n' +
      'If you\'re developing the tool, run: npm run build:template'
    );
  }

  if (verbose) {
    console.log(`  Template source: ${templateDir}`);
  }

  // Copy all template files to output directory
  copyDirectory(templateDir, outputDir, verbose);

  if (verbose) {
    console.log(`  ✓ Template copied to ${outputDir}`);
  }
}

/**
 * Find the template directory
 * Handles both development (local) and production (npm package) scenarios
 */
function findTemplateDirectory(): string {
  // Try local template directory first (development - in project root)
  const localTemplate = path.join(process.cwd(), 'template');
  if (fs.existsSync(localTemplate)) {
    return localTemplate;
  }

  // Try package template directory (production - npm installed)
  // When installed via npm, __dirname will be in node_modules/@inkorange/docspark/dist/cli/utils
  // So we need to go up 3 levels to get to the package root, then into template/
  const packageTemplate = path.join(__dirname, '../../../template');
  if (fs.existsSync(packageTemplate)) {
    return packageTemplate;
  }

  // Fallback for different installation scenarios
  const altTemplate = path.join(__dirname, '../../template');
  if (fs.existsSync(altTemplate)) {
    return altTemplate;
  }

  // Last resort: throw error with helpful message
  throw new Error(
    'Template directory not found. Searched in:\n' +
    `  - ${localTemplate}\n` +
    `  - ${packageTemplate}\n` +
    `  - ${altTemplate}`
  );
}

/**
 * Recursively copy directory contents
 */
function copyDirectory(src: string, dest: string, verbose?: boolean): void {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    // Skip metadata directory - it's already generated by the build command
    if (entry.isDirectory() && entry.name === 'metadata') {
      if (verbose) {
        console.log(`  ⊘ Skipping metadata directory (already generated)`);
      }
      continue;
    }

    // Skip README.md in template root
    if (!entry.isDirectory() && entry.name === 'README.md' && src === findTemplateDirectory()) {
      continue;
    }

    if (entry.isDirectory()) {
      copyDirectory(srcPath, destPath, verbose);
    } else {
      fs.copyFileSync(srcPath, destPath);
      if (verbose) {
        const relativePath = path.relative(src, srcPath);
        console.log(`  ✓ ${relativePath}`);
      }
    }
  }
}
